Ext.define('ExtJS6Class.view.user.UserReg',{
  extend:'Ext.form.Panel',
  alias:'widget.userreg',
  requires:['ExtJS6Class.view.user.UserRegController'],
  controller:'userreg',
  closable:true,
  bodyPadding:'5 5 5 5',
  title:'사용자등록',
  url:"../ServerPage/RegUser.jsp",
  items:[{
    xtype:'fieldset',
    title:'입력하세요',
    items:[{
      xtype:'textfield',
      fieldLabel:'사용자ID',
      labelAlign:'right',
      allowBlank:false,
      name:'userId',
    },{
      xtype:'textfield',
      fieldLabel:'닉네임',
      labelAligh:'right',
      allowBlank:false,
      name:'nickName',
    },{
      xtype:'textfield',
      fieldLabel:'패스워드',
      labelAlign:'right',
      allowBlank:false,
      name:'password',
    },{
      xtype:'textfield',
      fieldLabel:'이메일',
      labelAlign:'right',
      allowBlank:false,
      name:'email'
    }],
  }],
  buttons:[{
    text:'Reset',
    handler:'onReset'
  },{
    text:'Submit',
    formBind:true,
    disabled:true,
    handler:'onSubmit'
  }]
});